### ISSUE TITLE
Missing fabric.properties

### ISSUE THREAD

**Issue by hejunbinlan** [rallat/EffectiveAndroid#11]
Error:(9, 0) Missing fabric.properties, check the fabric.properties.sample file.

**Comment by swanhtet1992** [comment]
@hejunbinlan It is in the .gitignore file. Twitter consumers key are supposed to be generated on you own.
Create your own fabric.properties file as demonstrated [here](https://docs.fabric.io/android/fabric/integration.html#add-api-key-and-build-secret). Twitter consumer keys can be generated at apps.twitter.com.

**Comment by rallat** [comment]
@hejunbinlan follow @swanhtet1992 comment, he is totally right :)
